services:
  firestore:
    image: spine3/firebase-emulator
    ports:
      - 8080:8080
    volumes:
      - ./eq_cims_management_ui/devtools/firebase-emulator:/firebase
      - ./eq_cims_management_ui/devtools/firebase-emulator:/firebase/baseline-data
    networks:
      - eq-cir-fastapi_default

  eq-cims-management-ui:
    build: ./
    ports:
      - 5100:5100
    environment:
      - PORT=5100
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - CIR_API_BASE_URL=http://api-cir:3030
      - AUTHOR_REPUBLISH_API_URL=http://author-api-republish-mock:8081
    restart: on-failure
    depends_on:
      - firestore
    networks:
      - eq-cir-fastapi_default

networks:
  eq-cir-fastapi_default:
    external: true
