services:
  firestore:
    image: spine3/firebase-emulator
    ports:
      - 8080:8080
    volumes:
      - ./eq_cims_management_ui/devtools/firebase-emulator:/firebase
      - ./eq_cims_management_ui/devtools/firebase-emulator:/firebase/baseline-data

  eq-cims-management-ui:
    build: ./
    ports:
      - 5100:5100
    environment:
      - PORT=5100
      - FIRESTORE_EMULATOR_HOST=firestore:8080
    restart: on-failure
    depends_on:
      - firestore
