---
name: CI

permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: "${{ github.head_ref || github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-22.04
    env:
      FIRESTORE_EMULATOR_HOST: localhost:9090
      CIR_API_BASE_URL: localhost:3030
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: .python-version

      - name: Install Poetry
        run: python -m pip install poetry==2.1.2

      - name: Install Design System
        run: npm install

      - name: Install dependencies
        run: make install-dev

      - name: Lint Python
        run: make lint

      - name: Unit Tests
        run: make test-unit

      - name: Checkout eq-cir-fastapi
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: "ONSdigital/eq-cir-fastapi"
          ref: "main"
          path: "eq-cir-fastapi"

      - name: Docker compose CIR
        run: |
          cd eq-cir-fastapi
          ls -ls
          docker compose up --build -d

      - name: Checkout author-api-republish-mock
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: "ONSdigital/author-api-republish-mock"
          ref: "main"
          path: "author-api-republish-mock"

      - name: Docker compose Mock Author
        run: |
          cd author-api-republish-mock
          ls -ls
          docker compose up --build -d

      - name: Docker compose CIMS UI
        run: docker compose up --build -d

      - name: Functional Tests
        run: make test-functional

      - name: Docker compose CIMS UI shutdown
        run: docker compose kill

      - name: Docker compose CIR shutdown
        run: |
          cd eq-cir-fastapi
          docker compose kill

      - name: Docker compose CIR shutdown
        run: |
          cd author-api-republish-mock
          docker compose kill
